version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: hoge
      MYSQL_PASSWORD: fuga
      TZ: 'Asia/Tokyo'
    volumes:
    - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./data/sql:/sql
    ports:
    - 3306:3306

