version: '2'
services:
  apache:
    image: httpd:2.4.33
    container_name: apache
    ports:
      - "10080:80"
    volumes:
      - ./var/html/:/usr/local/apache2/htdocs/
      - ./var/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./var/.htdigest:/usr/local/apache2/.htdigest
      - ./var/.htpasswd:/usr/local/apache2/.htpasswd

